# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 286c905d2f8bec5e3ed73a496ee1532b8a16040376d1ad63df13f9228381b15ad524c3a32087165ec57435b9f84ac36c38894a6740af5222efe36acac2a360ba

test:
  secret_key_base: 37b580d1db73a7b12ebf38315dde692ec7e183bd04778fcbf928c96f50c5078632e1727fde26fff8e55c7e0b7d1c1808e963eff4d201c334d0d0c103cb7e86a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
